# Generated by Django 4.0.2 on 2022-02-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorelist',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
    ]
